Description: >
  This stack contains the RDS instance which will hold our application state
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC which owns the RDS SG
Resources:
  RdsWideOpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Accepting traffic from any place
      SecurityGroupIngress:
      - { CidrIp: 0.0.0.0/0, IpProtocol: -1 }
      Tags:
      - { Key: Name, Value: demodb-wide-open-sg }
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBName: foodb
      Engine: postgres
      EngineVersion: 9.6.5
      MasterUsername: foouser
      MasterUserPassword: foopassword
      PubliclyAccessible: true
      VPCSecurityGroups:
      - !Ref RdsWideOpenSecurityGroup
Outputs:
  DatabaseUrl:
    Description: A database connection string
    Value:
      Fn::Join:
      - ""
      - - "postgresql://foouser:foopassword"
        - "@"
        - !GetAtt Database.Endpoint.Address
        - ":"
        - !GetAtt Database.Endpoint.Port
        - "/foodb"
