Description: >
  This stack provisions the RDS instance which will be used by our app.
Resources:
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBName: !Ref AWS::StackName
      Engine: postgres
      EngineVersion: 9.6.5
      MasterUsername: rinkydink
      MasterUserPassword: smurfmagnet
      MultiAZ: true
      PubliclyAccessible: true
Outputs:
  DatabaseUrl:
    Description: A database connection string
    Value:
      Fn::Join:
      - ""
      - - "postgresql://rinkydink:smurfmagnet"
        - "@"
        - !GetAtt Database.Endpoint.Address
        - ":"
        - !GetAtt Database.Endpoint.Port
        - "/"
        - !Ref AWS::StackName
