
version: "2"
services:
  websvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgresql://postgres@websvcdb:5432/postgres
      - PORT=3000
    depends_on:
      - dockerize
    command:
        - "rails db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/opt/app
  websvcdb:
    image: postgres:9.6.5-alpine
  dockerize:
    image: jwilder/dockerize
    command: ["dockerize", "-wait", "tcp://websvcdb:5432", "-timeout", "50s"]
    depends_on:
      - websvcdb
      
